name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Type Check
        run: npm run typecheck

      - name: Run Tests
        run: npm test -- --passWithNoTests

      - name: Build
        run: npm run build
